# Generated by Django 4.1.7 on 2024-03-04 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('corpus', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('fileid', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
                ('n_tokens', models.IntegerField()),
                ('mean_surprisal', models.FloatField()),
                ('median_surprisal', models.FloatField()),
                ('mean_guesses', models.FloatField()),
                ('median_guesses', models.FloatField()),
                ('prop_guesses_5', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PassageToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
                ('gpt2_surprisal', models.FloatField(blank=True, null=True)),
                ('gpt2_guesses', models.IntegerField(blank=True, null=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwp.passage')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_index', models.IntegerField()),
                ('guess_token', models.CharField(max_length=100)),
                ('passage_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwp.passagetoken')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PassageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='incomplete', max_length=100)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwp.passage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwp.profile')),
            ],
        ),
    ]
