# Generated by Django 4.1.7 on 2024-03-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nwp', '0002_skip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skip',
            old_name='passageToken',
            new_name='passage_token',
        ),
    ]
